<?php

/**
 * @file
 * This module allows webforms to have a start and end date for their
 * submissions.
 *
 */

/**
 * Implements hook_permission().
 */
function webform_scheduler_permission() {
  return array(
    'schedule webforms' => array(
      'title' => t('Schedule webforms'),
      'description' => t('Change a webform\'s start and end date, allowing a webform to be scheduled.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter() for webform_configure_form().
 */
function webform_scheduler_form_webform_configure_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('schedule webforms')) {
    $start_date = time();
    $end_date = time();
    $settings = _webform_scheduler_webform_scheduler_settings($form['nid']['#value']);

    $form['#validate'][] = 'webform_scheduler_form_webform_configure_form_validate';
    $form['#submit'][] = 'webform_scheduler_form_webform_configure_form_submit';
    $form['#attached']['css'][] = backdrop_get_path('module', 'webform_scheduler') . '/css/webform_scheduler.admin.css';

    $start_date = (!empty($settings['begin_date'])) ? $settings['begin_date'] : NULL;
    $end_date = (!empty($settings['end_date'])) ? $settings['end_date'] : NULL;

    $form['scheduler'] = array(
      '#type' => 'fieldset',
      '#title' => t('Scheduler'),
      '#description' => t('Specify dates and times to schedule when users are allowed to use this webform.<br />If the webform\'s overall status is set to %Closed under Submission settings, it will remain closed regardless of Scheduler settings.', array(
        '%Closed' => t('Closed'),
      )),
      '#weight' => -2.5,
      '#collapsible' => TRUE,
      '#collapsed' => !isset($start_date) && !isset($end_date),
      '#tree' => TRUE,
    );

    $date_attributes = array(
      'date' => array(
        'min' => date('Y-m-d'),
        'max' => date('Y-m-d', strtotime('+3 years')),
        'placeholder' => t('e.g. @date', array(
          '@date' => format_date(REQUEST_TIME, 'custom', DATE_FORMAT_DATE)
        )),
      ),
      'time' => array(
        'placeholder' => t('e.g. @date', array(
          '@date' => format_date(REQUEST_TIME, 'custom', DATE_FORMAT_TIME)
        )),
      ),
    );

    $form['scheduler']['date_start'] = array(
      '#type' => 'html_datetime',
      '#title' => t('Start time'),
      '#default_value' => array(
          'date' => format_date($start_date, 'custom', DATE_FORMAT_DATE),
          'time' => format_date($start_date, 'custom', DATE_FORMAT_TIME),
        ),
      '#attributes' => $date_attributes,
    );

    $form['scheduler']['date_end'] = array(
      '#type' => 'html_datetime',
      '#title' => t('End time'),
      '#default_value' => array(
        'date' => format_date($end_date, 'custom', DATE_FORMAT_DATE),
        'time' => format_date($end_date, 'custom', DATE_FORMAT_TIME),
      ),
      '#attributes' => $date_attributes,
    );

    $form['scheduler']['restriction_method'] = array(
      '#type' => 'radios',
      '#title' => t('Access restriction method'),
      '#default_value' => isset($settings['restriction_method']) ? (int) $settings['restriction_method'] : 1,
      '#options' => array(
        0 => t('Deny access to the page'),
        1 => t('Allow access to the page, hide the webform'),
        2 => t('Allow access to the page, show the webform, disable components'),
      ),
    );

    $form['scheduler']['msg_before'] = array(
      '#type' => 'textfield',
      '#title' => t('Message to display before start date'),
      '#description' => t('Message to display before start date. Leave empty to use default message'),
      '#maxlength' => 128,
      '#default_value' => isset($settings['msg_before']) ? $settings['msg_before'] : '',
    );

    $form['scheduler']['msg_after'] = array(
      '#type' => 'textfield',
      '#title' => t('Message to display after end date'),
      '#description' => t('Message to display after end date. Leave empty to use default message'),
      '#maxlength' => 128,
      '#default_value' => isset($settings['msg_after']) ? $settings['msg_after'] : '',
    );

  }
}

/**
 * Additional validation handler for validating webform scheduler settings.
 */
function webform_scheduler_form_webform_configure_form_validate(&$form, &$form_state) {
  $values =& $form_state['values']['scheduler'];

  $values['date_start_timestamp'] = (!empty($values['date_start'])) ? date('U', strtotime(implode(' ', $values['date_start']))) : '';
  $values['date_end_timestamp'] = (!empty($values['date_end'])) ? date('U', strtotime(implode(' ', $values['date_end']))) : '';

  // If for some reason the user selected an end date that occurs before
  // the start date, they made a mistake.
  if (isset($values['date_start_timestamp'])
     && isset($values['date_end_timestamp'])
     && $values['date_end_timestamp'] <= $values['date_start_timestamp']) {
    form_set_error('date_end', t('The end time must be after the start time.'));
  }
}

/**
 * Additional submit handler for saving webform scheduler settings.
 */
function webform_scheduler_form_webform_configure_form_submit(&$form, &$form_state) {
  $values =& $form_state['values']['scheduler'];
  $settings = _webform_scheduler_webform_scheduler_settings($form['nid']['#value']);

  if (empty($settings) ||
    (isset($values['date_start_timestamp']) ? (int) $values['date_start_timestamp'] : 0) !== (int) $settings['begin'] ||
    (isset($values['date_end_timestamp']) ? (int) $values['date_end_timestamp'] : 0) !== (int) $settings['end'] ||
    (int) $values['restriction_method'] !== (int) $settings['restriction_method'] ||
    $values['msg_before'] !== $settings['msg_before'] ||
    $values['msg_after'] !== $settings['msg_after']) {
    $record = array(
      'nid' => $form['nid']['#value'],
      'begin_date' => isset($values['date_start_timestamp']) ? $values['date_start_timestamp'] : 0,
      'end_date' => isset($values['date_end_timestamp']) ? $values['date_end_timestamp'] : 0,
      'restriction_method' => (int) $values['restriction_method'],
      'msg_before' => trim($values['msg_before']) != ''?trim($values['msg_before']) : NULL,
      'msg_after' => trim($values['msg_after']) != ''?trim($values['msg_after']) : NULL,
    );

    // Insert or update the scheduler settings of this webform.

    backdrop_write_record('webform_scheduler', $record, empty($settings)?array() : 'nid');
  }
}

/**
 * Implements hook_node_view().
 */
function webform_scheduler_node_view($node, $view_mode) {
  if (!in_array($node->type, _webform_scheduler_node_types())) {
    return;
  }

  $settings = _webform_scheduler_webform_scheduler_settings($node->nid);

  if (!isset($node->webform['scheduler'])) {
    $node->webform['scheduler'] = array();
  }

  $node->webform['scheduler']['begin'] = isset($settings['begin']) ? (int) $settings['begin'] : 0;
  $node->webform['scheduler']['end'] = isset($settings['end']) ? (int) $settings['end'] : 0;
  $node->webform['scheduler']['restriction_method'] = isset($settings['restriction_method']) ? (int) $settings['restriction_method'] : 1;
  $node->webform['scheduler']['disabled'] = webform_scheduler_webform_disabled($node);
  $node->webform['scheduler']['msg_before'] = isset($settings['msg_before']) ? $settings['msg_before'] : '';
  $node->webform['scheduler']['msg_after'] = isset($settings['msg_after']) ?  $settings['msg_after'] : '';



  if ($node->webform['scheduler']['disabled']) {
    switch ($node->webform['scheduler']['restriction_method']) {
      case 0:
        backdrop_access_denied();
        break;
      case 1:
        $node->webform['status'] = 0;
      case 2:
        // @see webform_scheduler_form_webform_client_form_alter()
        if (($node->webform['scheduler']['begin'] > 0 && REQUEST_TIME < $node->webform['scheduler']['begin']) && $node->webform['scheduler']['msg_before'] != '') {
          backdrop_set_message(t($node->webform['scheduler']['msg_before']), 'warning');
        }
        elseif (($node->webform['scheduler']['end'] > 0 && REQUEST_TIME > $node->webform['scheduler']['end']) && $node->webform['scheduler']['msg_after'] != '') {
          backdrop_set_message(t($node->webform['scheduler']['msg_after']), 'warning');
        }
        break;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function webform_scheduler_form_webform_client_form_alter(&$form, &$form_state) {
  $node = $form['#node'];

  if (isset($node->webform['scheduler']) && $node->webform['scheduler']['disabled'] && $node->webform['status'] !== 0) {
    if ($node->webform['scheduler']['restriction_method'] === 2) {
      $form['#disabled'] = TRUE;
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function webform_scheduler_node_delete($node) {
  if (!in_array($node->type, _webform_scheduler_node_types())) {
    return;
  }

  db_delete('webform_scheduler')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Checks to see if the webform is disabled or not.
 *
 * @param int $node
 *   The node stdClass to which this webform belongs.
 * @return boolean
 *   TRUE if the webform under the node ID is disabled, FALSE otherwise.
 */
function webform_scheduler_webform_disabled($node) {
  if (($node->webform['scheduler']['begin'] > 0 && REQUEST_TIME < $node->webform['scheduler']['begin']) ||
      ($node->webform['scheduler']['end']   > 0 && REQUEST_TIME > $node->webform['scheduler']['end'])) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Fetch the scheduler settings and information of webform(s) by the node ID.
 *
 * @param int $nid
 *   The node ID to which the webform belongs.
 *
 * @return array
 *   A row of information represented as an associative array.
 */
function _webform_scheduler_webform_scheduler_settings($nid) {
  $db_settings = db_select('webform_scheduler', 'w', array('fetch' => PDO::FETCH_ASSOC))
    ->fields('w')
    ->condition('w.nid', $nid)
    ->execute()
    ->fetchAssoc();

  if ($db_settings) {
    $db_settings['begin'] = $db_settings['begin_date'];
    $db_settings['end'] =  $db_settings['end_date'];
  }

  return $db_settings;
}

/**
 * Get a list of Webform-enabled node types, with backwards compatibility.
 *
 * @see https://drupal.org/node/1609324#webform-types
 */
function _webform_scheduler_node_types() {
  if (function_exists('webform_node_types')) {
    return webform_node_types();
  }
  return webform_variable_get('webform_node_types');
}
